import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { cn } from "@/lib/utils";
import { ViewTransitions } from "next-view-transitions";
import Navbar from "@/components/nav";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const newsflashBB = localFont({
  src: "./fonts/NewsflashBB.ttf",
  variable: "--font-newsflash-bb",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        suppressHydrationWarning
        className={cn(
          geistSans.variable,
          geistMono.variable,
          newsflashBB.variable,
          "h-full antialiased"
        )}>
        <body suppressHydrationWarning className="min-h-full flex flex-col">
          {/* <LargeCover /> */}
          <Navbar />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
